### ISSUE TITLE
It seems to work until v. 2.0.11

### ISSUE THREAD

**Issue by fuomag9** [h0nus/BurpSuitePro-2.0.06-beta-Loader-Keygen#3]
I can't manage to make it work on versions higher than 2.0.11

**Comment by n0bodysec** [comment]
Interesting, I will have a look. I haven't any version higher than 2.0.11, can u send a link to download the .jar file?

Maybe the license system has changed a bit, but I can't check that.

Best regards.

**Comment by n0bodysec** [comment]
Excellent, thanks!
I will do some research now. Stay tuned!

Best regards.

**Comment by cr4ck32** [comment]
> Excellent, thanks!
> I will do some research now. Stay tuned!
> 
> EDIT: I downloaded the beta 2.0.15 and the keygen IS NOT working. Let me reverse that version and I'll try to find the new lic. system.
> 
> Best regards.
2_0_18beta, please!

Thanks!!!!

**Comment by h0nus** [comment]
Hi, sorry for delayed response, but actually PortSwigger has changed Licensing system from 2.0.11beta (excluded) to 2.0.19beta (latest at writing time).
Some help could be handful, because at the moment I'm reallly busy.
Sorry for the inconvenience!
@n0bodysec @cr4ck32 @fuomag9

**Comment by cr4ck32** [comment]
@h0nus   Please tell me in what way you could help? I have basic knowledge about reversing, if perhaps you can give me some clues or help tools to get the license algorithm, I would gladly do it.

**Comment by h0nus** [comment]
Actually i'm really busy, but over the 2.0.11 it doesn't work 'cause they have changed something and I don't have time to check again, can I close this issue?
