### ISSUE TITLE
CIL.StupidCryptor.Heur find by virustotal

### ISSUE THREAD

**Issue by Kidman1670** [h0nus/BurpSuitePro-2.0.06-beta-Loader-Keygen#5]
Find a nameless Cryptor name CIL.StupidCryptor.Heur find by virustotal. I dont find too much information about this cryptor but I think the uploader need to explain why this one exists.

https://www.virustotal.com/gui/file/1f3e31233e9920940a2fedb984a947fd1a9f8b3774738644c79567bb88087732/detection

**Comment by lorrangarcia** [comment]
It's look a false positive, but I not sure yet...

**Comment by R13TechNewbie** [comment]
Maybe this info could help...

http://community.sqlbackupandftp.com/t/virus-scanners-giving-false-positives/1299

**Comment by Kidman1670** [comment]
the link @R13TechNewbie share is about other software, it is not relative.
I think i sad a bit when i know a original key loader of burpsuite is very clean and the its author published in a underground hacking forum, but many people dowload it, insert something bad  and re-share it to communities, not even the key loader but the burpsuite pro app itself. So funny for people who tell:"I want to share free to help hacking community". Oh my god!!!how dare they can tell that. I try to just use it in a VM box, hope it wont make any damage.

[https://0x00sec.org/t/malware-reversing-burpsuite-keygen/5167](url)

**Comment by h0nus** [comment]
As you can see here there is the new scan of BurpKeygen.jar (hashes are the same)
https://www.virustotal.com/gui/file/b6278957d5271a223c7f3801de77a05ee9d95353551dcbfd019ea0101ebd9cdf/
And also HybridAnalyst Scan:
https://www.hybrid-analysis.com/sample/b6278957d5271a223c7f3801de77a05ee9d95353551dcbfd019ea0101ebd9cdf
If you don't trust this "software", just decompile it, analyze it and check network connection, but pay attention to a proxy on localhost:8080, could be really dangerous :O

**Comment by h0nus** [comment]
Closing for no responses
